In [2]:
from pytransform3d import rotations as pr
from pytransform3d import transformations as pt
import numpy as np

a_x = [1, 0, 0, np.pi/2]
R_x = pr.matrix_from_axis_angle(a_x)
print(f"R_x:{np.round(R_x)}")


a_y = [0, 1, 0, np.pi/2]
R_y = pr.matrix_from_axis_angle(a_y)
print(f"R_y:{np.round(R_y)}")

a_z = [0, 1, 0, np.pi/2]
R_z = pr.matrix_from_axis_angle(a_z)
print(np.round(R_z))

R = R_y@pr.matrix_from_axis_angle([1, 0, 0, -np.pi/2])
a_x_c = pr.compact_axis_angle(a_x)
a_y_c = pr.compact_axis_angle(a_y)
print(f"R:{np.round(R)}")
print(pr.axis_angle_from_matrix(R))
print(a_y_c -a_x_c)
print(pr.axis_angle_from_compact_axis_angle(a_y_c -a_x_c))
print('pr.compact_axis_angle_from_matrix(R):', pr.compact_axis_angle_from_matrix(R))

R_x:[[ 1.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]
R_y:[[ 0.  0.  1.]
 [ 0.  1.  0.]
 [-1.  0.  0.]]
[[ 0.  0.  1.]
 [ 0.  1.  0.]
 [-1.  0.  0.]]
R:[[ 0. -1.  0.]
 [ 0.  0.  1.]
 [-1. -0.  0.]]
[-0.57735027  0.57735027  0.57735027  2.0943951 ]
[-1.57079633  1.57079633  0.        ]
[-0.70710678  0.70710678  0.          2.22144147]
pr.compact_axis_angle_from_matrix(R): [-1.20919958  1.20919958  1.20919958]
