In [2]:
import numpy as np
from numpy.ma.core import shape

T = np.linspace(0, 1, 10)

In [6]:
T

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [5]:
print(T)
print(type(T))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
<class 'numpy.ndarray'>


In [25]:
Y = np.zeros((1001, 14))
T = np.linspace(0, 1, len(Y))
sigmoid = 0.5 * (np.tanh(1.5 * np.pi * (T - 0.5)) + 1.0)
radius = 0.5
circle1 = radius * np.cos(np.deg2rad(90) + np.deg2rad(90) * sigmoid)
circle2 = radius * np.sin(np.deg2rad(90) + np.deg2rad(90) * sigmoid)
print(T)
print(Y)
print(sigmoid)
print(radius)
print("circle1:", circle1)
print("circle2:", circle2)

[0.    0.001 0.002 ... 0.998 0.999 1.   ]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[0.00890331 0.00898686 0.00907119 ... 0.99092881 0.99101314 0.99109669]
0.5
circle1: [-0.00699242 -0.00705803 -0.00712425 ... -0.49994924 -0.49995018
 -0.4999511 ]
circle2: [0.4999511  0.49995018 0.49994924 ... 0.00712425 0.00705803 0.00699242]


In [24]:
Y[:, 0] = circle1
Y[:, 1] = 0.55
Y[:, 2] = circle2

In [26]:
np.linspace(0.0, 2.0, 101)

array([0.  , 0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 ,
       0.22, 0.24, 0.26, 0.28, 0.3 , 0.32, 0.34, 0.36, 0.38, 0.4 , 0.42,
       0.44, 0.46, 0.48, 0.5 , 0.52, 0.54, 0.56, 0.58, 0.6 , 0.62, 0.64,
       0.66, 0.68, 0.7 , 0.72, 0.74, 0.76, 0.78, 0.8 , 0.82, 0.84, 0.86,
       0.88, 0.9 , 0.92, 0.94, 0.96, 0.98, 1.  , 1.02, 1.04, 1.06, 1.08,
       1.1 , 1.12, 1.14, 1.16, 1.18, 1.2 , 1.22, 1.24, 1.26, 1.28, 1.3 ,
       1.32, 1.34, 1.36, 1.38, 1.4 , 1.42, 1.44, 1.46, 1.48, 1.5 , 1.52,
       1.54, 1.56, 1.58, 1.6 , 1.62, 1.64, 1.66, 1.68, 1.7 , 1.72, 1.74,
       1.76, 1.78, 1.8 , 1.82, 1.84, 1.86, 1.88, 1.9 , 1.92, 1.94, 1.96,
       1.98, 2.  ])

In [27]:
Y = np.empty((len(T), 2))
Y[:, 0] = np.cos(2.5 * np.pi * T)  #TODO:2.5*np.pi?
Y[:, 1] = 0.5 + np.cos(1.5 * np.pi * T)
Y[0]

array([1. , 1.5])

In [31]:
start_y = np.array([0.0])

In [35]:
start_y = np.array(0.0)
print(start_y)
print(type(start_y))
print(start_y.shape)

0.0
<class 'numpy.ndarray'>
()


In [1]:
import numpy as np
new_start = np.array([0.5, 0.5, 0, 1, 0, 0, 0, 0.5, 0.5, 0, 1, 0, 0, 0])
new_goal = np.array([-0.5, 0.5, 0, 1, 0, 0, 0, -0.5, 0.5, 0, 1, 0, 0, 0])
print(new_start[np.newaxis])
print(new_start[np.newaxis].shape)

[[0.5 0.5 0.  1.  0.  0.  0.  0.5 0.5 0.  1.  0.  0.  0. ]]
(1, 14)


In [8]:
a = np.zeros((3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
a = np.zeros([2,3])
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
random_state = np.random.RandomState(2)
print(random_state)

RandomState(MT19937)
