In [2]:
import numpy as np
import pytransform3d.rotations as pr

# 左右末端执行器初始姿态 对应关节空间（大致）
ee_left_start = np.array([
    [0.0, -1.0, 0.0, 0.75],
    [0.0, 0.0, -1.0, 0.0],
    [1.0, 0.0, 0.0, 0.28],
    [0.0, 0.0, 0.0, 1.0]
])
ee_right_start = np.array([
    [0.0, 1.0, 0.0, 0.75],
    [0.0, 0.0, 1.0, 0.0],
    [1.0, 0.0, 0.0, 0.28],
    [0.0, 0.0, 0.0, 1.0]
])

ee_left_start_a = pr.axis_angle_from_matrix(ee_left_start[:3, :3])
ee_right_start_a = pr.axis_angle_from_matrix(ee_right_start[:3, :3])
print(f"ee_left_start_a:\n{np.round(ee_left_start_a, decimals=4)}")
print(f"ee_right_start_a:\n{np.round(ee_right_start_a, decimals=4)}")

ee_left_start_a:
[ 0.5774 -0.5774  0.5774  2.0944]
ee_right_start_a:
[-0.5774 -0.5774 -0.5774  2.0944]


In [3]:
# 左右末端执行器初始姿态 对应关节空间（大致）
ee_left_start = np.array([
    [1.0, 0.0, 0.0, 0.75],
    [0.0, 1.0, 0.0, 0.0],
    [0.0, 0.0, 1.0, 0.28],
    [0.0, 0.0, 0.0, 1.0]
])
ee_left_start[:3, :3] = pr.matrix_from_axis_angle([0, 1, 0, np.deg2rad(-90)]) @ pr.matrix_from_axis_angle([1, 0, 0, np.deg2rad(90)])

ee_right_start = np.array([
    [1.0, 0.0, 0.0, 0.75],
    [0.0, 1.0, 0.0, 0.0],
    [0.0, 0.0, 1.0, 0.28],
    [0.0, 0.0, 0.0, 1.0]
])
# ee_left_start[:3, :3] = pr.matrix_from_axis_angle([0, 1, 0, np.deg2rad(90)])  # R(y,pi/2) y轴旋转90度
ee_right_start[:3, :3] = pr.matrix_from_axis_angle([0, 1, 0, np.deg2rad(-90)]) @ pr.matrix_from_axis_angle([1, 0, 0, np.deg2rad(-90)])
print(f"ee_left_start:\n{np.round(ee_left_start, decimals=4)}")
print(f"ee_right_start:\n{np.round(ee_right_start, decimals=4)}")

ee_left_start:
[[ 0.   -1.   -0.    0.75]
 [ 0.    0.   -1.    0.  ]
 [ 1.    0.    0.    0.28]
 [ 0.    0.    0.    1.  ]]
ee_right_start:
[[ 0.    1.   -0.    0.75]
 [ 0.    0.    1.    0.  ]
 [ 1.   -0.    0.    0.28]
 [ 0.    0.    0.    1.  ]]


In [5]:
# 左右末端执行器初始姿态 对应关节空间（大致）
# left
ee_left_start = np.array([
    [1.0, 0.0, 0.0, 0.70],
    [0.0, 1.0, 0.0, 0.2],
    [0.0, 0.0, 1.0, 0.28],
    [0.0, 0.0, 0.0, 1.0]
])
ee_left_start[:3, :3] = pr.matrix_from_axis_angle([1, -1, 1, np.deg2rad(120)])  # R(k,2/3*pi) k轴旋转120度

# right
ee_right_start = np.array([
    [1.0, 0.0, 0.0, 0.70],
    [0.0, 1.0, 0.0, -0.2],
    [0.0, 0.0, 1.0, 0.28],
    [0.0, 0.0, 0.0, 1.0]
])
ee_right_start[:3, :3] = pr.matrix_from_axis_angle([-1, -1, -1, np.deg2rad(120)])  # R(k,2/3*pi) k轴旋转120度

print(f"ee_left_start:\n{np.round(ee_left_start, decimals=4)}")
print(f"ee_right_start:\n{np.round(ee_right_start, decimals=4)}")

ee_left_start:
[[ 0.   -1.   -0.    0.7 ]
 [ 0.    0.   -1.    0.2 ]
 [ 1.    0.    0.    0.28]
 [ 0.    0.    0.    1.  ]]
ee_right_start:
[[ 0.    1.   -0.    0.7 ]
 [-0.    0.    1.   -0.2 ]
 [ 1.   -0.    0.    0.28]
 [ 0.    0.    0.    1.  ]]


In [3]:
# 左右末端执行器初始姿态 对应关节空间（大致）
ee_left_start = np.array([
    [0.0, -1.0, 0.0, 0.68],
    [0.0, 0.0, -1.0, 0.14],
    [1.0, 0.0, 0.0, 0.15],
    [0.0, 0.0, 0.0, 1.0]
])
ee_right_start = np.array([
    [0.0, 1.0, 0.0, 0.68],
    [0.0, 0.0, 1.0, -0.13],
    [1.0, 0.0, 0.0, 0.15],
    [0.0, 0.0, 0.0, 1.0]
])

ee_left_start_a = pr.axis_angle_from_matrix(ee_left_start[:3, :3])
ee_right_start_a = pr.axis_angle_from_matrix(ee_right_start[:3, :3])
print(f"ee_left_start_a:\n{np.round(ee_left_start_a, decimals=4)}")
print(f"ee_right_start_a:\n{np.round(ee_right_start_a, decimals=4)}")

ee_left_start_a:
[ 0.5774 -0.5774  0.5774  2.0944]
ee_right_start_a:
[-0.5774 -0.5774 -0.5774  2.0944]
