In [18]:
import numpy as np
import pytransform3d.rotations as pr
import pytransform3d.transformations as pt

In [19]:
q_left = [0.70562, 0.04029, 0.70634, -0.03944]
q_right = [-0.03999, 0.70638, 0.03973, -0.70559]
a_left = pr.axis_angle_from_quaternion(q_left)
a_right = pr.axis_angle_from_quaternion(q_right)

In [28]:
q_left1 = pr.quaternion_from_axis_angle([0, 1, 0, np.deg2rad(0)])
q_right1 = pr.quaternion_from_axis_angle([1, 0, -1, np.deg2rad(180)])

# q_right2 = pt.concat(pr.matrix_from_axis_angle([0, 0, 1, np.deg2rad(180)]), pr.matrix_from_quaternion
# (q_left1))
# R_three_fingers_front = pr.matrix_from_axis_angle([0, 0, 1, 0.5 * np.pi])
# R_to_center_start = pr.matrix_from_axis_angle([1, 0, 0, np.deg2rad(-180)])
# R_to_center_end = pr.matrix_from_axis_angle([1, 0, 0, np.deg2rad(-270)])
# q_start = pr.quaternion_from_matrix(R_three_fingers_front.dot(R_to_center_start))
R_three_fingers_front = pr.matrix_from_axis_angle([0, 0, 1, np.deg2rad(90)])
R_to_center_start = pr.matrix_from_axis_angle([1, 0, 0, np.deg2rad(90)])
q_right2 = pr.quaternion_from_matrix(R_three_fingers_front.dot(R_to_center_start))
print(q_left)
print(q_left1)
print(q_right)
print(q_right1)
print(q_right2)

[0.70562, 0.04029, 0.70634, -0.03944]
[1. 0. 0. 0.]
[-0.03999, 0.70638, 0.03973, -0.70559]
[ 6.12323400e-17  7.07106781e-01  0.00000000e+00 -7.07106781e-01]
[0.5 0.5 0.5 0.5]
